### ISSUE TITLE
Missing  Dimension in DataLoader 

### ISSUE THREAD

**Issue by NatchapolShinno** [chihina/PJAE-ICCV2023#2]
Hello,

I encountered an error while trying to implement your project. Here's the traceback:

```
  Traceback (most recent call last):
  File "/home/slab/joint_att/train.py", line 342, in <module>
    _ = process_epoch(epoch, training_data_loader, 'train')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slab/joint_att/train.py", line 109, in process_epoch
    out_head = model_head(batch)
               ^^^^^^^^^^^^^^^^^
  File "/home/slab/anaconda3/envs/joint_att/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slab/joint_att/models/head_pose_estimator.py", line 37, in forward
    batch_size, frame_num, people_num, channel_num, img_height, img_width = head_img.shape
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 5)
```
Then, I checked the dataset file in the __getitem__ :
```    
        print("head_img.shape")
        return data
```

The result was torch.Size([12, 3, 64, 64]). However, in train.py:

```
print("===> Loading datasets")
train_set = dataset_generator(cfg, 'train')
print(cfg.exp_set.batch_size)
training_data_loader = DataLoader(dataset=train_set,
                                batch_size=cfg.exp_set.batch_size,
                                shuffle=True, 
                                num_workers=cfg.exp_set.num_workers,
                                pin_memory=False)

for batch in training_data_loader:
    print(batch["head_img"].shape)
    break
```

I checked again after the dataloader and got torch.Size([4, 12, 3, 64, 64]). It seems that the frame_num dimension is missing.

My question is, when is the frame_num going to be added? It appears that the tensor has only five dimensions. Thank you in advance for your assistance.

**Comment by chihina** [comment]
Thank you for your interest in our work.

While I implemented the frame_num dimension after the submission, the frame_num dimension is not used in the PJAE.
Therefore, I deleted the codes related to the frame_num dimension.

If you have more questions, feel free to ask easily.

**Comment by NatchapolShinno** [comment]
Thank you for your answer, but after I deleted the frame_num, I encountered another error:

```
Traceback (most recent call last):
  File "/home/slab/joint_att/train.py", line 343, in <module>
    _ = process_epoch(epoch, training_data_loader, 'train')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slab/joint_att/train.py", line 128, in process_epoch
    out_attention = model_attention(batch)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slab/anaconda3/envs/joint_att/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slab/joint_att/models/joint_attention_estimator_transformer_dual_only_people.py", line 313, in forward
    trans_att_people_people_i = people_people_trans_weights.view(self.batch_size, 1, people_num+1, people_num+1)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[8, 1, 4, 4]' is invalid for input of size 2048

```
I've checked the size of the 'people_people_trans_weights' variable, and it returns "torch.Size([8, 16, 16])". Shouldn't it be [8, 4, 4]? If I'm not misunderstanding, I've been struggling with this error for a while. Thank you in advance again for your help.

**Comment by chihina** [comment]
The error also happened to me after deleting the frame_num.
However, I fixed the error yesterday and pushed the latest codes to this repository.
Could you pull our latest codes from the repository again?
Do not hesitate to contact me again if you have any questions.

**Comment by NatchapolShinno** [comment]
Thank you very much !
